### COMMON SETTINGS
VLAN: '0'
DOMAIN: '<DOMAIN>'
NTP_SERVER: '<NTP_SERVER>'
PARENT_VC: '<PARENT_VC>'

### NESTED VCSA DEPLOYMENT DATA
VC_ESX_HOST: '<VC_ESX_HOST>'
VC_ESXI_USR: 'root'
VC_ESXI_PWD: '<MASTER_PASSWORD>'
VC_ESXI_DATASTORE: '<VC_ESXI_DATASTORE>'
VC_DEPLOYMENT_SIZE: 'tiny'
VC_THIN_PROVISION: True
VC_NET_MODE: 'static'
VC_NAME: 'n-vcsa7'
VC_SYSTEM_NAME: 'n-vcsa7.<DOMAIN>'
VC_IP: '<VC_IP>'
VC_NETMASK: '25'
VC_DNS_SERVERS:
  - '<VC_DNS_SERVERS>'
  - '8.8.8.8'
VC_GATEWAY: '<VC_GATEWAY>'
VC_PORTGROUP: '<VC_PORTGROUP>'
VC_ROOT_PWD: '<MASTER_PASSWORD>'
VC_SSH_ENABLED:  True
VC_SSO_USER: 'administrator@vsphere.local'
VC_SSO_PWD: '<MASTER_PASSWORD>'
VC_SSO_DOMAIN: 'vsphere.local'
CEIP_ENABLED:  False
VC_ISO_PATH: '<VC_ISO_PATH>/VMware-VCSA-all-7.0.0-15952498.iso'
VC_ISO_MOUNT: "/tmp/tmp_iso"

VC_DATACENTER: 'n-datacenter'
VC_CLUSTER:  'n-cluster'

### Section for esx-deploy.py
ESX_VM_NAME_PREFIX: "n-esx7-"
ESX_VM_HOSTNAME_PREFIX: "n-esx7-"
ESX_TARGET_VCSA_SSO_USER: "administrator@vsphere.local"
ESX_TARGET_VCSA_SSO_PASS: "<<MASTER_PASSWORD>>"
ESX_IPS:
  - '<ESX_IP_1>'
  - '<ESX_IP_2>'
ESX_NETMASK: '255.255.255.128'
ESX_GATEWAY: '<ESX_GATEWAY>'
ESX_ISO_PATH: '<VC_ISO_PATH>/Nested_ESXi7.0_Appliance_Template_v1.ova'
ESX_DATASTORE: '<VC_ESXI_DATASTORE>'

### Section for VDS & DVPG
VDS_NAME: 'wcp-vds-1'
VDS_UPLINK: 'vmnic1'
VDS_PG1_NAME: 'management-vm'
VDS_PG1_VLAN: 0
VDS_PG2_NAME: 'tep-edge'
VDS_PG2_VLAN: 102
VDS_PG3_NAME: 'ext-uplink-edge'
VDS_PG3_VLAN: 101